# Generated by Django 2.1.7 on 2019-03-23 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='uesr',
            new_name='user',
        ),
    ]
