# Generated by Django 2.1.7 on 2019-03-23 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190323_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_in_minutes',
            new_name='time_minutes',
        ),
    ]
